#ifndef STATE_H
#define STATE_H

#include <stdint.h>

typedef uint8_t STATE;
enum state {
	STATE_MENU_MAIN,
	STATE_MENU_SINGLE_OPTIONS,
	STATE_MENU_MULTI_OPTIONS,
	STATE_GAME_SINGLE_INIT,
	STATE_GAME_SINGLE_PLAY,
	STATE_GAME_SINGLE_POST,
	STATE_GAME_MULTI_INIT,
	STATE_GAME_MULTI_PLAY,
	STATE_GAME_MULTI_POST,
	STATE_EXIT
};

#endif
